### PR TITLE
564 program menu

### PR DESCRIPTION
**Pull request by axoplasm**
Addresses #564 

-- Commits before 10/16 refactor some navbar layout to be more BEM
-- @KennyMonster's commits implement `select2` library for multiselect/search functionality
-- Commits in last two days crib select2 sass for inclusion in our master stylesheet…
-- …including a new “dark” theme specified as an option on the navbar selectbox

Ideally we will retire select2 or load its css as a module at compile time instead of globbing it into the master stylesheet. select2‘s sass is not well structured for package management; cribbing a whole library like this is not my preferred way to operate.

### CODE REVIEW

**Comment by axoplasm** [comment]
I'll ping @jennyhavah for feedback. This is relatively easy to change. The teal is most on-brand. Here's what the new dropdown in "dark" theme looks like:

image

**Comment by KennyMonster** [comment]
On second thought, we are already using that teal w/ white text for buttons, so I can't imagine anyone would have a hard time with it.

**Comment by sanjuroj** [comment]
@axoplasm There seems to be more margin around the dropdown menu items in the navbar, and the color is a slightly darker grey on the new version than the old, which is whiter.

**Comment by axoplasm** [comment]
@sanjuroj this branch caught some changes to the navbar when I standardized the gray palette. I was more concerned about visual regressions in the select2 selects (e.g. IPTT quickstart select elements). The intended effect is:

* No more rounded corners
* Standardized grays (this is very subtle in most cases)
* highlight is now the brand teal, not select2's Facebooky blue

**Comment by jennyhavah** [comment]
@axoplasm No strong opinions about teal vs gray, as long as the contrast is high enough to pass common standards. (The only shade of MC teal that worked for me was the very darkest one, and that was borderline depending on font size.)

**Comment by jennyhavah** [comment]
@axoplasm I suggest we shorten "Go to program or country" to "Programs and countries" The "Go to" seems extraneous and might cause "countries" to be truncated in some languages.

**Pull request merged**
