### PR TITLE
Run suite on all browsers with one command

### PR DESCRIPTION
**Pull request by kurtwall**
As a quick start, this PR attempts to automate setting up and configuring the test environment and then running all of the tests for all of the defined browsers. If I've done this correctly, anyone with a development system, the browsers they want to test installed, and a working NodeJS/NPM environment _should_ be to do:

- `git checkout merge-test`
- `cd test/js`
- Edit config.json appropriately
- `make install`
- `./node_modules/.bin/wdio`

The last step starts the server, runs the complete test suite for each browser, then terminates the server and exits after showing the test results.

### CODE REVIEW

**Comment by kurtwall** [comment]
The output I get looks like this.
```
$ ./node_modules/.bin/wdio 
․․․․․․․․․․․․․․․․․․․․․․․F․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․F․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․F․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․F․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․

124 passing (258.70s)
204 skipped
4 failing

1) TolaActivity Program Indicators page should have matching indicator counts on data button and in table:
Cannot read property 'ELEMENT' of null
running chrome
running firefox
TypeError: Cannot read property 'ELEMENT' of null
    at $("table.hiddenTable") - at element("table.hiddenTable") - $.js:42:17

2) Indicator Targets Targets tab should *not* require target Baseline if "Not applicable" *is* checked:
An element could not be located on the page using the given search parameters ("p").
running chrome
running firefox
Error: An element could not be located on the page using the given search parameters ("p").
    at getText() - index.js:312:3
```

**Comment by mahmoodkhan** [comment]
The instruction in the README were pretty clear and didn't have to guess how to set things up. Also, when I ran the test command, I get the following as output:

I am not sure whether the test command actually starts the selenium server; I think I had to manually start the selenium server, which is OK. just making sure we have it documented correctly in the README.

```
․․․․․․․․․․․․․․․․․․․․․․F․․F․․․․․․․․F․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․F․․

67 passing (233.10s)
93 skipped
4 failing

1) TolaActivity Program Indicators page should toggle PIs table by clicking PI Indicators button:
An element could not be located on the page using the given search parameters ("a.btn.btn-sm.btn-success").
running firefox
Error: An element could not be located on the page using the given search parameters ("a.btn.btn-sm.btn-success").
    at Promise.F (node_modules/core-js/library/modules/_export.js:35:28)
    at getAttribute("data-target") - at Context.<anonymous> (test/specs/indicators.js:100:38)

2) TolaActivity Program Indicators page should have matching indicator counts on data button and in table:
Indicator count mismatch: expected 27 to equal 0
running firefox
AssertionError: Indicator count mismatch: expected 27 to equal 0
    at /Users/mkhan/dev/TolaActivity/TolaActivity/test/js/test/specs/indicators.js:132:14
    at Promise.F (/Users/mkhan/dev/TolaActivity/TolaActivity/test/js/node_modules/core-js/library/modules/_export.js:35:28)
    at Promise.F (/Users/mkhan/dev/TolaActivity/TolaActivity/test/js/node_modules/core-js/library/modules/_export.js:35:28)
    at Promise.F (/Users/mkhan/dev/TolaActivity/TolaActivity/test/js/node_modules/core-js/library/modules/_export.js:35:28)

3) TolaActivity Program Indicators page Programs dropdown should have same items as Programs table:
expected 'EC - Economic Opportunities for Afghan Uprooted People' to equal 'EC'
running firefox
AssertionError: expected 'EC - Economic Opportunities for Afghan Uprooted People' to equal 'EC'
    at Context.<anonymous> (/Users/mkhan/dev/TolaActivity/TolaActivity/test/js/test/specs/indicators.js:52:16)
    at Promise.F (/Users/mkhan/dev/TolaActivity/TolaActivity/test/js/node_modules/core-js/library/modules/_export.js:35:28)

4) Indicator Targets Targets tab "Event" target frequency should default "Number of events" to 1:
Did not receive expected number of target events: expected 1 to equal ''
running firefox
AssertionError: Did not receive expected number of target events: expected 1 to equal ''
    at Context.<anonymous> (/Users/mkhan/dev/TolaActivity/TolaActivity/test/js/test/specs/targets.js:545:16)
    at Promise.F (/Users/mkhan/dev/TolaActivity/TolaActivity/test/js/node_modules/core-js/library/modules/_export.js:35:28)
```

**Comment by kurtwall** [comment]
Thanks @mahmoodkhan! 🥇  I think a couple of those errors will go away with the latest test updates I have in another branch. I need to update the README for the latest state of the code, but this branch was just a spike to see what would be involved.

**Comment by kurtwall** [comment]
I've updated the README.  We now have a few options for running tests:
# The Big Green Button - 3 commands, run the entire suite on all the browsers we support with a minimal amount of setup
# Do the manual setup as described in the README and then start the server and the testrunner yourself. This runs the entire against the requested browsers.
# Do the manual setup described in the README, start the server, run individual test files

**Pull request merged**
